name: Trigger Personal Site Rebuild

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Site Rebuild
        run: |
          curl -X POST https://api.github.com/repos/garcia5/personal-site/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: token ${{ secrets.PERSONAL_SITE_PAT }}' \
          -d '{"event_type": "dotfiles_update"}'
